# Generated by Django 5.2.3 on 2025-06-29 10:19

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cartitem_wishlistitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlistitem',
            old_name='added_at',
            new_name='added_on',
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='session_key',
            field=models.CharField(db_index=True, default=datetime.datetime(2025, 6, 29, 10, 19, 13, 355959, tzinfo=datetime.timezone.utc), max_length=40),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together={('user', 'product')},
        ),
    ]
