# Generated by Django 5.2.3 on 2025-06-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_added_at_wishlistitem_added_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitem',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
